FROM node:alpine as builder 
WORKDIR '/app'
COPY package.json .
RUN npm install 
COPY . .
RUN npm run build

EXPOSE 4040
CMD ["sh", "-c", "npm run prisma:generate && npm run prisma:db:seed && npm run start:prod"]
